spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0
  security:
    oauth2:
      client:
        registration:
          wso2:
            scope: openid patient admin doctor
            authorization-grant-type: authorization_code
            client-name: WSO2 Identity Server
            client-id: hBkFcKhxwQRbtHq3XrTMotgpygka
            client-secret: RhHVKTEzhEkYiMpE826iYHJlhQMa
            redirect-uri: '{baseUrl}/login/oauth2/code/wso2'
        provider:
          wso2:
            jwk-set-uri: https://localhost:9443/oauth2/jwks
            authorization-uri: https://localhost:9443/oauth2/authorize
            token-uri: https://localhost:9443/oauth2/token
            user-info-uri: https://localhost:9443/oauth2/userinfo
client:
  post-logout-uri: http://localhost:8080/spring-boot-sample/login
healt-first-api:
  host: https://localhost:8246/backend/1.0.0/

security:
  oauth2:
    host: https://localhost:9446/oauth2/token
    client:
      client-id: a07pdaqb3JxxSEKk4uXNbSMR4KYa
      secret-id: JPEdXOZP_s_Ka31DxbhjqCHZgX8a
      patient:  #ok
        user: rushmin
        password: password
      doctor: #ok ultron
        user: ultron
        password: password
      admin: #ok
        user: admin
        password: admin
